[project]
name = "rfmeter"
version = "0.1.0"
description = "ImmersionRC RF Power Meter logger"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
    "pyqt5>=5.15.11",
    "pyserial>=3.5",
]
